### PR TITLE
2024-12-21-UVAFluX-Ensemble

### PR DESCRIPTION
**Pull request by aniruddhadiga**
Adding seasonal targets - peak week and peak incidence

### CODE REVIEW

**Comment by aniruddhadiga** [comment]
I have left the "horizon" and "target_end_date" column blank. The "output_type_id" for the peak week is specified as date in ISO format. The validations are failing due to the seasonal targets. Please suggest how to rectify.

**Comment by Annabella-Hines** [comment]
I believe the error is because the only valid dates for output_type_id for the peak week target are the ones within the challenge period, so only dates between 2024-11-23 and 2025-05-31 are accepted. I think removing the extra dates should also fix the other error, but I will keep an eye on you submission if any more issues pop up!

**Comment by Annabella-Hines** [comment]
I apologize for not being fully clear with my previous comment, the peak week target requires all the weeks within the challenge period range, and the probabilities should sum to 1 for each location as well.

**Comment by aniruddhadiga** [comment]
There is still some issue. I have removed the seasonal target for now and submitted. Can we submit the updated file with seasonal targets tomorrow?

**Comment by Annabella-Hines** [comment]
Normally the deadline is midnight on Wednesdays but if you can get the seasonal targets to work by 9 am tomorrow we can still accept it. I will keep an eye out to help with more troubleshooting if necessary in the morning!

**Comment by aniruddhadiga** [comment]
Great, thanks!

**Pull request merged**
