### PR TITLE
CEID Walk Model Metadata

### PR DESCRIPTION
**Pull request by victorceid**

### CODE REVIEW

**Comment by victorceid** [comment]
Hello, I would like to approve this model that we intent to use on weekly submissions. Thank you.

**Comment by Annabella-Hines** [comment]
Hello, it looks like there was an error with the license provided, here are the accepted values: 
- "CC0-1.0",
- "CC-BY-4.0"
- "CC-BY_SA-4.0"
- "PPDL"
- "ODC-by"
- "ODbL"
- "OGL-3.0"

**Comment by victorceid** [comment]
I just changed the license, thank you.

Also, do you know when the NHSH cases for the current week will be available?

**Comment by Annabella-Hines** [comment]
The preliminary hospitalization data is released around noon EST, and the target data file in this repo is typically updated by 12:30.

**Comment by victorceid** [comment]
Sorr, I'm not understanding the issue now. I don't have any line with: UGA_CEID-UGA_CEID_Walk

**Comment by victorceid** [comment]
I think now it will work

**Comment by Annabella-Hines** [comment]
I think the issue now is that the file name needs to match the "team_abbr-model_abbr, so I believe if you change the file name to "UGA_CEID-Walk.yml" it should work

**Comment by victorceid** [comment]
Thank you, I just did that.

**Pull request merged**
