### PR TITLE
CEPH_2024-11-23 After data ajustments

### PR DESCRIPTION
**Pull request by paulocv**

### CODE REVIEW

**Comment by Annabella-Hines** [comment]
@zkamvar Could you take a look at this error?

**Comment by zkamvar** [comment]
😞 I'm sorry. The immediate solution is to re-run this check.

**Comment by zkamvar** [comment]
The longer-term solution is to update your workflows. I will make a PR for that. 

In short, we [started using the R-universe for package distribution](https://github.com/orgs/hubverse-org/discussions/30) back in September, and we even updated the GitHub actions workflows on our end so that they only use the R-universe distributions. Unfortunately, I neglected to make a clear announcement for hub administrators to update your workflows, which means that you've been getting the development version of hubValidations and all other packages.

**Comment by Annabella-Hines** [comment]
Ah okay, thank you for the help!

**Pull request merged**
