### PR TITLE
Update flu forecasts 2024-12-11

### PR DESCRIPTION
**Pull request by nikosbosse**
Automated flu forecast submission from Metaculus

### CODE REVIEW

**Comment by zkamvar** [comment]
Hi @nikosbosse if you update your branch to the current `main`, the validations will start to run again. See #1253 for details.

**Comment by nikosbosse** [comment]
Ah I missed this, sorry. The validations are now rejected because the latest commit is outside of the allowed time window

**Comment by Annabella-Hines** [comment]
All good, I will go ahead and merge since it was an issue on our end!

**Comment by nikosbosse** [comment]
Thank you!

**Pull request merged**
