### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ye-chen-netsci**

### CODE REVIEW

**Comment by rborchering** [comment]
Hello, please see validations error. It appears that you are missing a metadata file.

**Comment by rborchering** [comment]
On the previous PR, it appears that there was a formatting issue in your metadata file:  LosAlamos_NAU-CModel_Flu.yml: Metadata file contents must match consistent
  with schema specifications parse error: after array element, I expect ',' or
  ']' d_model" "data_inputs", "methods", " (right here) ------^

**Comment by rborchering** [comment]
If helpful, please also see notes on how to run validations locally, at these links:
•	https://github.com/cdcepi/FluSight-forecast-hub/blob/main/model-output/README.md#Forecast-validation
•	https://github.com/cdcepi/FluSight-forecast-hub/tree/main/model-metadata#Data-validation

**Comment by ye-chen-netsci** [comment]
Hi Rebecca, Thank you for providing the steps from the page. I followed
them closely and used the package to validate my yml file, as well as the
existing yml files from other teams. Unfortunately, I encountered the same
error message. I've double-checked to ensure I didn't overlook anything, so
it seems there might be a bug in the code. Could you please take a look or
advise on the next steps?

**Pull request closed without merging**
