### PR TITLE
Flusight baseline 12-14-2024

### PR DESCRIPTION
**Pull request by Annabella-Hines**

### CODE REVIEW

**Comment by Annabella-Hines** [comment]
@zkamvar sorry to bother you again, I just can't find what the issue is with this. It was generated the same way as previous weeks' submissions were

**Comment by zkamvar** [comment]
I'll take a look 👀

**Comment by zkamvar** [comment]
It is indeed very strange. This is what the results say is missing.

``` r
library(gert)
#> Linking to libgit2 v1.8.1, ssh support: YES
#> Global config: /Users/zkamvar/.gitconfig
#> Default user: Zhian N. Kamvar (UMass) <zkamvar@umass.edu>
library(withr)
library(hubValidations)

tmp <- tempfile()
git_clone("https://github.com/cdcepi/FluSight-forecast-hub.git", tmp)
with_dir(tmp, system("gh pr checkout 1261"))
res <- with_dir(tmp, validate_pr(gh_repo = "cdcepi/FluSight-forecast-hub", pr_number = 1261))

options(width = 120)
print(res$req_vals$missing, n = Inf)
#> # A tibble: 53 × 7
#>    reference_date horizon target          target_end_date location output_type output_type_id
#>    <date>           <int> <chr>           <date>          <chr>    <chr>       <chr>         
#>  1 2024-12-14          -1 wk inc flu hosp NA              01       sample      <NA>          
#>  2 2024-12-14          -1 wk inc flu hosp NA              02       sample      <NA>          
#>  3 2024-12-14          -1 wk inc flu hosp NA              04       sample      <NA>          
#>  4 2024-12-14          -1 wk inc flu hosp NA              05       sample      <NA>          
#>  5 2024-12-14          -1 wk inc flu hosp NA              06       sample      <NA>          
#>  6 2024-12-14          -1 wk inc flu hosp NA              08       sample      <NA>          
#>  7 2024-12-14          -1 wk inc flu hosp NA              09       sample      <NA>          
#>  8 2024-12-14          -1 wk inc flu hosp NA              10       sample      <NA>          
#>  9 2024-12-14          -1 wk inc flu hosp NA              11       sample      <NA>          
#> 10 2024-12-14          -1 wk inc flu hosp NA              12       sample      <NA>          
#> 11 2024-12-14          -1 wk inc flu hosp NA              13       sample      <NA>          
#> 12 2024-12-14          -1 wk inc flu hosp NA              15       sample      <NA>          
#> 13 2024-12-14          -1 wk inc flu hosp NA              16       sample      <NA>          
#> 14 2024-12-14          -1 wk inc flu hosp NA              17       sample      <NA>          
#> 15 2024-12-14          -1 wk inc flu hosp NA              18       sample      <NA>          
#> 16 2024-12-14          -1 wk inc flu hosp NA              19       sample      <NA>          
#> 17 2024-12-14          -1 wk inc flu hosp NA              20       sample      <NA>          
#> 18 2024-12-14          -1 wk inc flu hosp NA              21       sample      <NA>          
#> 19 2024-12-14          -1 wk inc flu hosp NA              22       sample      <NA>          
#> 20 2024-12-14          -1 wk inc flu hosp NA              23       sample      <NA>          
#> 21 2024-12-14          -1 wk inc flu hosp NA              24       sample      <NA>          
#> 22 2024-12-14          -1 wk inc flu hosp NA              25       sample      <NA>          
#> 23 2024-12-14          -1 wk inc flu hosp NA              26       sample      <NA>          
#> 24 2024-12-14          -1 wk inc flu hosp NA              27       sample      <NA>          
#> 25 2024-12-14          -1 wk inc flu hosp NA              28       sample      <NA>          
#> 26 2024-12-14          -1 wk inc flu hosp NA              29       sample      <NA>          
#> 27 2024-12-14          -1 wk inc flu hosp NA              30       sample      <NA>          
#> 28 2024-12-14          -1 wk inc flu hosp NA              31       sample      <NA>          
#> 29 2024-12-14          -1 wk inc flu hosp NA              32       sample      <NA>          
#> 30 2024-12-14          -1 wk inc flu hosp NA              33       sample      <NA>          
#> 31 2024-12-14          -1 wk inc flu hosp NA              34       sample      <NA>          
#> 32 2024-12-14          -1 wk inc flu hosp NA              35       sample      <NA>          
#> 33 2024-12-14          -1 wk inc flu hosp NA              36       sample      <NA>          
#> 34 2024-12-14          -1 wk inc flu hosp NA              37       sample      <NA>          
#> 35 2024-12-14          -1 wk inc flu hosp NA              38       sample      <NA>          
#> 36 2024-12-14          -1 wk inc flu hosp NA              39       sample      <NA>          
#> 37 2024-12-14          -1 wk inc flu hosp NA              40       sample      <NA>          
#> 38 2024-12-14          -1 wk inc flu hosp NA              41       sample      <NA>          
#> 39 2024-12-14          -1 wk inc flu hosp NA              42       sample      <NA>          
#> 40 2024-12-14          -1 wk inc flu hosp NA              44       sample      <NA>          
#> 41 2024-12-14          -1 wk inc flu hosp NA              45       sample      <NA>          
#> 42 2024-12-14          -1 wk inc flu hosp NA              46       sample      <NA>          
#> 43 2024-12-14          -1 wk inc flu hosp NA              47       sample      <NA>          
#> 44 2024-12-14          -1 wk inc flu hosp NA              48       sample      <NA>          
#> 45 2024-12-14          -1 wk inc flu hosp NA              49       sample      <NA>          
#> 46 2024-12-14          -1 wk inc flu hosp NA              50       sample      <NA>          
#> 47 2024-12-14          -1 wk inc flu hosp NA              51       sample      <NA>          
#> 48 2024-12-14          -1 wk inc flu hosp NA              53       sample      <NA>          
#> 49 2024-12-14          -1 wk inc flu hosp NA              54       sample      <NA>          
#> 50 2024-12-14          -1 wk inc flu hosp NA              55       sample      <NA>          
#> 51 2024-12-14          -1 wk inc flu hosp NA              56       sample      <NA>          
#> 52 2024-12-14          -1 wk inc flu hosp NA              72       sample      <NA>          
#> 53 2024-12-14          -1 wk inc flu hosp NA              US       sample      <NA>
```

<sup>Created on 2024-12-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Annabella-Hines** [comment]
Is that an issue with how sample is specified in tasks.json? Like the compound task id set or something?

**Comment by zkamvar** [comment]
> Is that an issue with how sample is specified in tasks.json? Like the compound task id set or something?

I'm not sure. I am investigating and will get back to you unless @elray1 or @nickreich has any insight.

**Comment by elray1** [comment]
Thanks for tagging me. My reading of the situation is that it wants the sample outputs to include a horizon of -1.  I don't have an immediate understanding of why the validation results would be different this week than last week, but one relevant thing that may have changed is the upgrade to the v4 schema.  Is it possible that something about the identification of which horizons are required for samples changed with this update?

**Comment by zkamvar** [comment]
It's definitely a problem with v4 and on @elray1's suggestion, I tested this after reverting the config back to v3:

``` r
library(gert)
#> Linking to libgit2 v1.8.1, ssh support: YES
#> Global config: /Users/zkamvar/.gitconfig
#> Default user: Zhian N. Kamvar (UMass) <zkamvar@umass.edu>
library(withr)
library(hubValidations)

tmp <- tempfile()
git_clone("https://github.com/cdcepi/FluSight-forecast-hub.git", tmp)
with_dir(tmp, system("gh pr checkout 1261"))
f <- "https://raw.githubusercontent.com/cdcepi/FluSight-forecast-hub/4ba10b69b3940a835f73124c9c1995b72fe24af4/hub-config/tasks.json"
f2 <- "https://raw.githubusercontent.com/cdcepi/FluSight-forecast-hub/4ba10b69b3940a835f73124c9c1995b72fe24af4/hub-config/admin.json"
download.file(f, fs::path(tmp, "hub-config", "tasks.json"), overwrite = TRUE)
download.file(f2, fs::path(tmp, "hub-config", "admin.json"), overwrite = TRUE)
res <- with_dir(tmp, validate_pr(gh_repo = "cdcepi/FluSight-forecast-hub", pr_number = 1261))
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
#> ℹ Updating superseded URL `Infectious-Disease-Modeling-hubs` to `hubverse-org`
check_for_errors(res)
#> ✔ All validation checks have been successful.
```

<sup>Created on 2024-12-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by zkamvar** [comment]
I've opened #1270 to revert the config back to v3 so that this can go through until we test this further.

**Pull request merged**
