### PR TITLE
Revert "switch to v4; fix schema org URL"

### PR DESCRIPTION
**Pull request by zkamvar**
This reverts commit 4ef66b8c523c02d10cfa8327ba3c9bc8b6fdbc0a.

See https://github.com/cdcepi/FluSight-forecast-hub/pull/1261#issuecomment-2537242929 for details and rationale.

### CODE REVIEW

**Comment by elray1** [comment]
I note that the validations themselves passed:
image

The check failure is due to a separate issue in a following step about commenting on the PR.

**Comment by zkamvar** [comment]
agreed.

**Comment by elray1** [comment]
@Annabella-Hines @smathis14 @rborchering I'm going to defer to you all to merge this in since you are the owners of the repo.  But just to be clear, the idea of this PR is to roll back to version 3.0.1 of the hubverse schema rather than v4.  Once this PR has been merged in, you should be able to re-run validations on the FluSight-baseline submission for this week (e.g. by closing and re-opening that PR, #1261) and get a passing result.

We will work on sorting out the validations issue that came up, and we can try again with the v4 upgrade later.  Sorry for the inconvenience here!

**Comment by Annabella-Hines** [comment]
Thank you both for your help on this, we definitely appreciate the quick response!

**Comment by zkamvar** [comment]
We have officially released the fix and it should be generally available within the hour: https://github.com/hubverse-org/hubValidations/releases/tag/v0.10.0

Sorry again for the mixup

**Pull request merged**
