### PR TITLE
UGA_CEID-Walk_2024_12_07

### PR DESCRIPTION
**Pull request by victorceid**

### CODE REVIEW

**Comment by victorceid** [comment]
Thank you, I just did that.

**Comment by Annabella-Hines** [comment]
The target should be "wk inc flu hosp" with a separate column titled horizon that specifies what week is being forecasted in relation to the reference_date. This week, horizon 0 would have 2024-12-07 as the target_end_date, horizon 1 would be 2024-12-14, etc.

**Comment by victorceid** [comment]
Thank you! I corrected this. I hope now it is ok.

**Comment by Annabella-Hines** [comment]
Looks good, thank you for the submission!

**Pull request merged**
