### PR TITLE
Weekly Uploads

### PR DESCRIPTION
**Pull request by ameiyappan-gh**

### CODE REVIEW

**Comment by AWebber1** [comment]
Looks like your only issue is that the license section of your metadata is incorrectly formatted. Quick fix there and you should be set!
- Alex

**Comment by ameiyappan-gh** [comment]
yes! will do it right now!

**Comment by AWebber1** [comment]
Looks like your file name is "GH-model", but the model_id is "GH-svm_model". These need to be the same. - Alex

**Comment by AWebber1** [comment]
Beautifully done! - Alex

**Comment by ameiyappan-gh** [comment]
Thank you! have a good night!

**Pull request merged**
