### PR TITLE
email change on metadata for MDPredict

### PR DESCRIPTION
**Pull request by EnspikondPlus**

### CODE REVIEW

**Comment by Annabella-Hines** [comment]
@zkamvar is this an issue coming from updating the schema?

**Comment by zkamvar** [comment]
The solution at the moment is to hard-code runner back to `ubuntu-22.04`

**Comment by zkamvar** [comment]
I'll make a PR

**Comment by Annabella-Hines** [comment]
@zkamvar it is still showing the same error after rerunning after merging your recent pr

**Comment by zkamvar** [comment]
It's because it's running from the workflow file on the fork, which still needs to be updated. 

@EnspikondPlus, can you go to https://github.com/EnspikondPlus/mdpredict-flusightfork/tree/main and synchronize your repository?

**Pull request merged**
